// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Testing', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Testing', async function() {
    // Test name: Testing
    // Step # | name | target | value
    // 1 | open | / | 
    await driver.get("http://localhost:5000/")
    // 2 | setWindowSize | 1936x1048 | 
    await driver.manage().window().setRect({ width: 1936, height: 1048 })
    // 3 | click | linkText=Login | 
    await driver.findElement(By.linkText("Login")).click()
    // 4 | click | id=email | 
    await driver.findElement(By.id("email")).click()
    // 5 | type | id=email | danish@gmail.com
    await driver.findElement(By.id("email")).sendKeys("danish@gmail.com")
    // 6 | click | id=password | 
    await driver.findElement(By.id("password")).click()
    // 7 | type | id=password | 1234
    await driver.findElement(By.id("password")).sendKeys("1234")
    // 8 | sendKeys | id=password | ${KEY_ENTER}
    await driver.findElement(By.id("password")).sendKeys(Key.ENTER)
    // 9 | click | linkText=Subscriptions | 
    await driver.findElement(By.linkText("Subscriptions")).click()
    // 10 | click | id=endDate | 
    await driver.findElement(By.id("endDate")).click()
    // 11 | type | id=endDate | 2024-08-20
    await driver.findElement(By.id("endDate")).sendKeys("2024-08-20")
    // 12 | click | css=.btn-primary | 
    await driver.findElement(By.css(".btn-primary")).click()
  })
})
